### PR TITLE
Option for square particle textures

### PR DESCRIPTION
**Pull request by ShaunNoWay**
This creates a new cvar, "r_oldparticles" to make some particle textures be a simple square, like in the old software renderer. It also randomly makes each bullet impact particle one of three colors: dark grey, medium grey or light grey, also like in the software renderer.

The effect looks best when bilinear texture filtering is turned off. Here's a video:
https://youtu.be/lWvydpCxqxs

All changes are commented, "ADDOLDPARTICLES". **Edit:** Removed these comments. I didn't know GitHub automatically detected changes in code.

Sorry if my code is inefficient or unconventional. I'm a beginner at this programming stuff.

**Edit:** Accidentally deleted the branch. Oops. It's back up now. Sorry about that.

### CODE REVIEW

**Comment by mittorn** [comment]
Hello. I have tested this, it works fine. Can you merge these commits into one or few? There are many changes that removed by later commits  It can make difficults with merge/rebase branches.

**Comment by ShaunNoWay** [comment]
I'm sorry, I'm not quite sure what you mean. Do you mean to paste my changes into a newer version of the source code? Or something else?

Again, I'm sorry. I'm terribly new to this GitHub stuff.

**Comment by mittorn** [comment]
Just get diff for these commits, make new branch and apply it with patch. After that make new commit and new pull request.

**Comment by ShaunNoWay** [comment]
This pull request is up to date with the master branch. Do you mean to add these changes onto your [3153 Update](https://github.com/SDLash3D/xash3d/compare/3153update) branch? If so, I can totally do that.

**Comment by a1batross** [comment]
Here is a git squash exists. :)

Also... What is the purpose.of square particles? It cannot be made through client library?

**Comment by ShaunNoWay** [comment]
Hmm, I'll look up that Git squash thing.

The purpose is aesthetics. I personally like to play with bilinear filtering off, and I felt that the default blurry particles looked out of place against an otherwise pixel-y world.

I couldn't make custom particle textures using the Half-Life SDK, as the particle texture seems to be hard-coded into the engine (both in GoldSrc and Xash3D).

**Comment by mittorn** [comment]
https://github.com/SDLash3D/xash3d/pull/60#issuecomment-143907572, please wait, downloader_3153 will be merged to master soon.

**Comment by ShaunNoWay** [comment]
Sure thing. I'll wait.

**Comment by mittorn** [comment]
downloader merged now.

**Comment by ShaunNoWay** [comment]
Ah, okay. I had some trouble getting my fork to update with the base branch, so I kinda just put it down and forgot about it. I'll work on that later today.

**Pull request closed without merging**
