### PR TITLE
Android port

### PR DESCRIPTION
**Pull request by a1batross**

### CODE REVIEW

**Comment by JoelTroch** [comment]
Does this port can be built ? If yes are there are any specific requirement (I have Eclipse with Android SDK/NDK) ? I would like to test in on my Moto X (1st gen) ^_^

**Comment by a1batross** [comment]
Just look to the xash3d-android-project repository.
And here is a prebuilt version https://yadi.sk/d/YKM6-7GGfesFU
Put valve folder from your steam HalfLife folder to /sdcard/xash and enjoy.
There is many bugs so it is not fully playable.

**Comment by JoelTroch** [comment]
Everything runs pretty fine for a prototype ^_^

**Comment by a1batross** [comment]
Thanks for the feedback! ;)

**Pull request merged**
