### PR TITLE
Fix of pfnDrawStringReverse

### PR DESCRIPTION
**Pull request by GAMELASTER**
A for function used a initial declaration what is enabled only in C11 or C99, so i maked declaration before for.

### CODE REVIEW

**Comment by nekonomicon** [comment]
Hmm...
-char * szIt = str;
+char *szIt;

**Comment by GAMELASTER** [comment]
@nekonomicon 
Yes, the declaration needs to be outside of for.

**Comment by nekonomicon** [comment]
@GAMELASTER, It seems you do not understand me. Your patch correct but needs remove dublicate initialization.

**Comment by mittorn** [comment]
Same fix already in code-clean2 branch, will be merged after some time

**Pull request closed without merging**
