### PR TITLE
Clean up, bugfixes, some enhancements from DarkPlaces

### PR DESCRIPTION
**Pull request by UCyborg**
Sorry for virtually large amount of changes, first commit mostly just changes bunch of strings and comment text (grammar, spelling etc.). They happened to be lying on my hard drive since last year. Probably the last one of that kind since one could do that all day and not get any real work done.

### CODE REVIEW

**Comment by a1batross** [comment]
Wow! Such a big commits. It will take time to review.

**Comment by UCyborg** [comment]
Just noticed that they weren't used anywhere else. I know, just a bunch of details that don't make much difference in practice.

**Comment by UCyborg** [comment]
Ok, do you mind if I just fix existing commit or is it better if I make new one?

**Comment by UCyborg** [comment]
Oh, there is also one useless comment in host.c, didn't notice the first time that you redefined SetCurrentDirectory to chdir on Linux...

**Comment by a1batross** [comment]
So there is no problems for me. Everything works fine on Linux and Android. 
Waiting for review from @mittorn.

**Comment by UCyborg** [comment]
Awesome!

**Pull request merged**
